<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d4yii2\sqlreport\models\base;

use d4yii2\sqlreport\models\SqlreportQuery;
use Yii;
use yii\db\ActiveRecord;

/**
 * This is the base-model class for table "sqlreport".
 *
 * @property integer $id
 * @property integer $sys_company_id
 * @property string $name
 * @property string $sql
 * @property string $notes
 * @property string $aliasModel
 */
abstract class Sqlreport extends ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'sqlreport';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'smallint Unsigned' => [['id','sys_company_id'],'integer' ,'min' => 0 ,'max' => 65535],
            [['sql', 'notes'], 'string'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('sqlreport', 'ID'),
            'sys_company_id' => Yii::t('sqlreport', 'Sys Company ID'),
            'name' => Yii::t('sqlreport', 'Name'),
            'sql' => Yii::t('sqlreport', 'Sql'),
            'notes' => Yii::t('sqlreport', 'Notes'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \d4yii2\sqlreport\models\SqlreportQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new SqlreportQuery(get_called_class());
    }

}
